### ISSUE TITLE
Design a vector(SVG) logo for this project

### ISSUE THREAD

**Issue by akamhy** [akamhy/videohash#43]
Please design a vector logo for this project.
The logo must contain the project name 'videohash'. 

You must release the logo under the MIT License(same license as the project).

I **want the output in SVG and PNG formats**. The logo must be transparent(the background) and should be professional. 

Examples of logos of some real projects that I like. The new logo can be of a similar design but **MUST NOT be exactly copied**.
  - https://commons.wikimedia.org/wiki/File:OpenCV_Logo_with_text_svg_version.svg
  - https://commons.wikimedia.org/wiki/File:TensorFlowLogo.svg
  - https://commons.wikimedia.org/wiki/File:NumPy_logo_2020.svg
 
Both the PNG and SVG formats should be **inside the assets directory** in the pull request.
<s>
**This issue is not gonna get assigned before you open a pull request** but the one I like the most is gonna be selected. **Please open a pull request only if you are good at making vector logos.**</s> Thank you!

**Comment by akamhy** [comment]
You can ask your questions here.

**Comment by iconolocode** [comment]
Here are some idea sketches for the logo:

![SmartSelect_20211016-005427_Samsung Notes](https://user-images.githubusercontent.com/90782137/137562528-744d84a6-d954-4557-9fa6-3418b6da5a6e.jpg)
---
Design notes:

The top is more abstract and dynamic while the logos at the bottom are more detailed but less creative.

The similarity between two videos is the central theme of the logos. The color green is used to convey this. The other colors are based on the substractive color model.

1,2,3:
The three first logos explore different color palettes. The first two are pretty similar but for the first one the "outside" colors are saturated and for the second one the inverse, the color in the middle is the one that is saturated. The yellow may be changed since it pops out a bit too much on a dark background. The third one has a more calm palette.

The colors on the rest of the sketches are not final, just to indicate the placement.

The first three are based on the hashtag symbol. The parallel lines aren't placed in a way to have equal "outside triangles". This would give the logo a more star-like shape and make the two video frames less clear. The contrast between the small and big triangles create some dynamism in the design.
4,5,6: some other options regarding the film roll lengths. But these don't look as good as the first ones so I didn't develop them further.

This design however could create confusion regarding the bigger angle than 10 degrees limitation of the software.

7,8,9:
To find an alternative that hasn't this problem, the three last logos were designed with a horizontal arrangement. The overlap of the two videos is smaller, because else they could be interpreted as a layer effect instead of two separate files.

The video play button can have multiple meanings here. Links of similar things between the two videos, or a zoom on a specific part of the video. The last logo is even more literal, being closer to the real analog object.

These logos are less innovative. There is a high probability of other logos having similar designs. Though two video frames together is a simple concept and would be difficult to be considered as plagiarism.


Having the examples of logos you liked in mind, I think the first three are the most suitable. They have in common a dynamic composition with a lot of angles.

---

The name VideoHash should be added in the final design.

Concerning the SVG format, I plan to use a graphical vector editor and optimise the files with a program meant for that.
What your requirements for making good vector logos are is unclear to me. If my process isn't what you are looking for and you except that the SVG code itself gets edited, it would be better if somebody more experienced in that language carries on with making the logo.

That's it for today,
Sorry for the long text

**Comment by iconolocode** [comment]
Thank you for the clarifications.

I will proceed now with making a vector version of the first design and report back here.

**Comment by akamhy** [comment]
> The colors may have some tweaking, they look quite different on my screens, so I am unsure about it. Edit: maybe make the text blue so that it's more visible in dark mode
> 
> Tell me what you think

I like the one on the top left. And the font color should not be black because of the issue with dark mode but blue or purple.
